# Languages: e.g. en, zh-Hans
language: "en"

authKey: you_should_change_this

ktor:
  host: "127.0.0.1"
  port: 65360

qqBots:
  - host: "127.0.0.1"
    port: 65361
    ssl: true
    groupName: "Group Name 0"
    groupCode: 3692432137
    default: true
  - host: "127.0.0.1"
    port: 65361
    ssl: false
    groupName: "Group Name 1"
    groupCode: 3842465973
    default: false

minecraftServers:
  - serverName: "Server Name 0"
    host: "127.0.0.1"
    port: 65362
    ssl: false
    default: true
  - serverName: "Server Name 1"
    host: "127.0.0.1"
    port: 65363
    ssl: false
    default: false
