name: Build dev version artifacts
on: [pull_request, push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3.9.0
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Show Java version
        run: java -version
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.3.3
        with:
          cache-disabled: true
      - name: Show Gradle version
        run: ./gradlew --version
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - name: Get short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: RemoteMC-Core-${{ env.SHORT_SHA }}
          path: build/distributions
