name: Build Beta version and release it

on:
  push:
    tags:
      - '!.*v[0-9]+\.[0-9]+\.[0-9]+.*'
      - 'v[0-9]+\.[0-9]+\.[0-9]+-beta'
      - 'v[0-9]+\.[0-9]+\.[0-9]+-beta\.[0-9]+'

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          17,    # Current Java LTS
        ]
        # and run only on macOS
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Show Java version
        run: java -version
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.8.1
        with:
          cache-disabled: true
      - name: Show Gradle version
        run: ./gradlew --version
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - name: Get Tag
        uses: mad9000/actions-find-and-replace-string@3
        id: gettag
        with:
          source: ${{ github.ref }}
          find: 'refs/tags/'
          replace: ''
      - name: Get Version Number
        uses: mad9000/actions-find-and-replace-string@3
        id: getversion
        with:
          source: ${{ steps.gettag.outputs.value }}
          find: 'v'
          replace: ''
      - name: Get Version (Beta with numeric identifiers)
        uses: frabert/replace-string-action@v2.4
        id: getversion-beta
        with:
          string: ${{ steps.getversion.outputs.value }}
          pattern: '-beta\.'
          replace-with: ' Beta '
      - name: Get Version (Beta without numeric identifiers)
        uses: frabert/replace-string-action@v2.4
        id: getversion-beta-no-numeric
        with:
          string: ${{ steps.getversion-beta.outputs.replaced }}
          pattern: '-beta'
          replace-with: ' Beta'
      - name: Get short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: SHA to upper case
        id: sha
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.SHORT_SHA }}
      - name: Release
        uses: ncipollo/release-action@v1.13.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          name: "Version ${{ steps.getversion-beta-no-numeric.outputs.replaced }} (${{ steps.sha.outputs.uppercase }})"
          artifacts: "build/distributions/*.jar"
          bodyFile: "RELEASE_NOTE.md"
          prerelease: true
