name: Build dev version artifacts
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          17,    # Current Java LTS
        ]
        # and run on Linux, macOS, and Windows
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Show Java version
        run: java -version
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.8.0
        with:
          cache-disabled: true
      - name: Show Gradle version
        run: ./gradlew --version
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - name: Get short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Upload Artifacts
        if: ${{ runner.os == 'macOS' }} # Only upload artifacts built on macOS
        uses: actions/upload-artifact@v3
        with:
          name: RemoteMC-Core-${{ env.SHORT_SHA }}
          path: build/distributions
